name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          cd packages/client-mav && npm ci
          cd ../site-visualizations && npm ci
      - name: Build MAV
        working-directory: packages/client-mav
        run: |
          npm run build:libs
          npm run build -- --base-href=/demo/
      - name: Build Site Visualizations
        working-directory: packages/site-visualizations
        run: npm run build -- --base-href=/site-visualizations/

      - name: Package Site
        run: |
          cp -r packages/website-static dist
          cp -r packages/client-mav/dist/client-mav dist/demo
          cp -r packages/site-visualizations/dist/site-visualizations dist/site-visualizations
          cp dist/index.html dist/404.html

      - uses: jsmrcaga/action-netlify-deploy@v1.8.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          use_nvm: false
          build_command: echo
          install_command: echo
          build_directory: dist
